package com.dev.ws.mathservice2014;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-12T22:16:03.409-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "mathservice2014", 
                  wsdlLocation = "http://www.example.org/?wsdl",
                  targetNamespace = "http://ws.dev.com/mathservice2014/") 
public class Mathservice2014_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.dev.com/mathservice2014/", "mathservice2014");
    public final static QName Mathservice2014SOAP = new QName("http://ws.dev.com/mathservice2014/", "mathservice2014SOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace/eclipse/weblogic/ws-ex/src/main/resources/schema/com/dev/ws/provider/mathservice2014.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Mathservice2014_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/eclipse/weblogic/ws-ex/src/main/resources/schema/com/dev/ws/provider/mathservice2014.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Mathservice2014_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Mathservice2014_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Mathservice2014_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Mathservice2014_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Mathservice2014_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Mathservice2014_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Mathservice2014
     */
    @WebEndpoint(name = "mathservice2014SOAP")
    public Mathservice2014 getMathservice2014SOAP() {
        return super.getPort(Mathservice2014SOAP, Mathservice2014.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Mathservice2014
     */
    @WebEndpoint(name = "mathservice2014SOAP")
    public Mathservice2014 getMathservice2014SOAP(WebServiceFeature... features) {
        return super.getPort(Mathservice2014SOAP, Mathservice2014.class, features);
    }

}
