package com.dev.ws.mathservice2014;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-05-13T22:00:51.246-04:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://ws.dev.com/mathservice2014/", name = "mathservice2014")
@XmlSeeAlso({ObjectFactory.class})
public interface Mathservice2014 {

    @WebMethod(action = "http://ws.dev.com/mathservice2014/add")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.dev.com/mathservice2014/", className = "com.dev.ws.mathservice2014.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.dev.com/mathservice2014/", className = "com.dev.ws.mathservice2014.AddResponse")
    @WebResult(name = "out", targetNamespace = "")
    public int add(
        @WebParam(name = "valOne", targetNamespace = "")
        int valOne,
        @WebParam(name = "valTwo", targetNamespace = "")
        int valTwo
    );
}
