//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.02 at 10:38:26 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dev.com/oxm/domain", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package example.eai.trading.oxm.domain;
