//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.28 at 09:07:21 PM EDT 
//


package example.eai.trading.oxm.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QuoteRequest" type="{http://www.dev.com/oxm/domain}QuoteRequestType" minOccurs="0"/>
 *         &lt;element name="TradeRequest" type="{http://www.dev.com/oxm/domain}TradeRequestType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestType", propOrder = {
    "quoteRequest",
    "tradeRequest"
})
public class RequestType {

    @XmlElement(name = "QuoteRequest")
    protected QuoteRequestType quoteRequest;
    @XmlElement(name = "TradeRequest")
    protected TradeRequestType tradeRequest;

    /**
     * Gets the value of the quoteRequest property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteRequestType }
     *     
     */
    public QuoteRequestType getQuoteRequest() {
        return quoteRequest;
    }

    /**
     * Sets the value of the quoteRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteRequestType }
     *     
     */
    public void setQuoteRequest(QuoteRequestType value) {
        this.quoteRequest = value;
    }

    /**
     * Gets the value of the tradeRequest property.
     * 
     * @return
     *     possible object is
     *     {@link TradeRequestType }
     *     
     */
    public TradeRequestType getTradeRequest() {
        return tradeRequest;
    }

    /**
     * Sets the value of the tradeRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeRequestType }
     *     
     */
    public void setTradeRequest(TradeRequestType value) {
        this.tradeRequest = value;
    }

}
